### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by phongtran91nt**
Comment

### CODE REVIEW

**Comment by HE1-SIM** [comment]
ThunderCore is very Good..👍👍

**Comment by vinodchaun** [comment]
Hi

**Comment by Ngathu452000** [comment]
Hey. ....

**Comment by Lamonpalas** [comment]
Es una mejor aplicación para minar
Saludos

**Comment by gunel26** [comment]
very good ı love you thunder

**Comment by waguinhopbi** [comment]
Ui, hollo

**Comment by wildtazempires** [comment]
Comment;

**Comment by wildtazempires** [comment]
Comment

**Review by Juny-34 — APPROVED** [review]

**Comment by Hamza2107** [comment]
Hello

**Comment by annikavasquez** [comment]
How to use? How to create link to send. 😔😔 I dont know what to do

**Comment by Kingsyaitan1992** [comment]
Good project.. less fees..

**Comment by fiishGOD** [comment]
mantap jiwaa

**Comment by uyat99** [comment]
ThunderCore are amazing apps, i always open this apps every hour. If you ask, i think i would be wonderful if Dev Team, add some more additional task so that user can improve their token earn🤝👍

**Comment by uyat99** [comment]
> ThunderCore are amazing apps, i always open this apps every hour. If you ask, i think i would be wonderful if Dev Team, add some more additional task so that user can improve their token earn🤝

**Comment by flywiz15** [comment]
this app is cool, just found the app that is so interesting and exciting. keep it up ❤️

**Comment by MURADKHAN69** [comment]
Really very good project

**Comment by dedeyansyah** [comment]
I hope ThunderCore can be the greatest token 🚀🚀 # ThunderCore good

**Comment by milleniait** [comment]
I like to see a modern centred learning architecture on thundercore.
I habe a blueprint for a prototype.

**Comment by Sanusisul** [comment]
ThunderCore are wonderful apps, I have a strong believe in this app and i am introducing this to all my family and friends.
Love life ThundeeCore🤝

**Comment by MrManteka** [comment]
Algún español que sepa cómo funciona esto?

**Pull request closed without merging**
