### PR TITLE
Thundercore

### PR DESCRIPTION
**Pull request by abgarko**
Its really a great project but more features should be added like thundercore chat zone, thundercore news e.t.c

### CODE REVIEW

**Comment by Carloshector9711** [comment]
Nice

**Comment by MollyEmpress** [comment]
This project is great

**Comment by Tomash0** [comment]
Nice

**Comment by Treasure-l** [comment]
Woww!!! What a wonderful project. It will get a lot better if accept ERC20 and BEP20 tokens

**Comment by martinez260** [comment]
Buena app

**Comment by Daiane13pereira** [comment]
Ótimo projeto
0xbaf03cae3195ebb454aceec04b5a3dd1955930e5

**Comment by krypt14** [comment]
I think thunder token should be available on listed on BSC

**Comment by Anntrang** [comment]
Good day , perfect performance https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-123456789

**Comment by hasanome** [comment]
https://github.com/hasanome/ome
Nice♥… Good Earning App

**Comment by hasanome** [comment]
nice

**Comment by hasanome** [comment]
A naming system like ENS so that I can use human-readable addresses"

**Pull request closed without merging**
